name: Deploy to Linux via SSH

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Set up SSH connection
        uses: webfactory/ssh-agent@v0.5.2
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEYS }}
         
      - name: Add known hosts
        run: echo "${{ secrets.SSH_PRIVATE_KEYS }}" >> $HOME/.ssh/known_hosts
          
      - name: Create destination directory
        uses: appleboy/ssh-action@master
        with:
          host: 95.85.121.201
          port: 2222
          username: ${{ secrets.SSH_USENAME }}
          key: ${{ secrets.SSH_PRIVATE_KEYS }}
          script: |
            # Проверяем, существует ли папка /home/test/destination
            if [ ! -d "/home/test/destination" ]; then
              mkdir /home/test/destination
            else
              echo "Directory /home/test/destination already exists. Skipping mkdir."
            fi
                  
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Copy files via SSH
        uses: appleboy/scp-action@master
        with:
          host: 95.85.121.201
          port: 2222
          username: ${{ secrets.SSH_USENAME }}
          key: ${{ secrets.SSH_PRIVATE_KEYS }}
          source: "*"
          target: "/home/test/destination"
                  
#      - name: Copy files via SSH with password using expect
#        env:
#          PASS_KEY: ${{ secrets.PASS_KEY }}
#        run: |
#          ssh-keyscan -p 2222 -H 95.85.121.201 >> $HOME/.ssh/known_hosts
#          echo "${{ secrets.SSH_KEY }}" >> $HOME/.ssh/known_hosts
#          chmod 600 $HOME/.ssh/id_rsa
#          scp -r -P 2222 -i $HOME/.ssh/id_rsa docker-compose1.yaml install.sh ${{ secrets.SSH_USENAME }}@95.85.121.201:/home/test/destination
            
#      - name: List remote directory contents
#        run: |
#          ssh -p 2222 -i ${{ secrets.SSH_PRIVATE_KEYS }} ${{ secrets.SSH_USENAME }}@95.85.121.201 ls /home/test/destination

      - name: SSH into the server and run script
        uses: appleboy/ssh-action@master
        with:
          host: 95.85.121.201
          port: 2222
          username: ${{ secrets.SSH_USENAME }}
          key: ${{ secrets.SSH_PRIVATE_KEYS }}
          script: |
            cd /home/test/destination
            sudo chmod +x install.sh
            sudo ./install.sh
            echo "Deployment completed."
