name: Deploy to Linux via SSH

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Set up SSH connection
        uses: webfactory/ssh-agent@v0.5.1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add known hosts
        run: echo "${{ secrets.SSH_KEY }}" >> $HOME/.ssh/known_hosts

      - name: Copy files via SSH
        uses: appleboy/scp-action@master
        with:
          host: 95.85.121.201
          port: 2222
          username: ${{ secrets.SSH_USENAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: docker-compose1.yaml
          target: /home/test/destination
          timeout: 30s
          command_timeout: 10m
          use_insecure_cipher: false
          rm: false
          debug: false
          strip_components: 0
          overwrite: false
          tar_dereference: false
          tar_exec: tar
          proxy_port: 22
          proxy_timeout: 30s
          proxy_use_insecure_cipher: false

      - name: SSH into the server and run script
        uses: appleboy/ssh-action@master
        with:
          host: 95.85.121.201
          port: 2222
          username: ${{ secrets.SSH_USENAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/test/destination
            chmod +x install.sh
            ./install.sh

      - name: Clean up temporary key file
        run: rm temp_key
