name: Deploy to Linux via SSH

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Set up SSH connection
        uses: webfactory/ssh-agent@v0.5.1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEYS }}

      - name: Copy files via SSH
        run: scp -r -P 2222 -i ${{ secrets.SSH_PRIVATE_KEYS }} docker-compose.yaml install.sh test@95.85.121.201:/path/to/destination

      - name: SSH into the server and run script
        uses: appleboy/ssh-action@master
        with:
          host: 95.85.121.201
          port: 2222
          username: test
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /path/to/destination
            chmod +x install.sh
            ./install.sh
