name: Deploy to Linux via SSH

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Set up SSH connection
        uses: webfactory/ssh-agent@v0.5.1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEYS }}
          
      - name: Create destination directory
        uses: appleboy/ssh-action@master
        with:
          host: 95.85.121.201
          port: 2222
          username: ${{ secrets.SSH_USENAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            mkdir -p /home/test/destination
            
      - name: Create temporary key file
        run: echo "$SSH_PRIVATE_KEY" > temp_key
            
      - name: Copy files via SSH
        run: scp -r -P 22 -i temp_key docker-compose.yaml install.sh ${{ secrets.SSH_USENAME }}@95.85.121.201:/home/test/destination

      - name: SSH into the server and run script
        uses: appleboy/ssh-action@master
        with:
          host: 95.85.121.201
          port: 2222
          username: ${{ secrets.SSH_USENAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/test/destination
            chmod +x install.sh
            ./install.sh
            
      - name: Clean up temporary key file
        run: rm temp_key
