name: Deploy to Linux via SSH

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.2
        with:
          key: {%- raw -%} ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Copy files via SSH
        run: |
          ssh -p 2222 ${{ secrets.SSH_USENAME }}@95.85.121.201 'mkdir -p /path/to/destination'
          scp -P 2222 -r docker-compose.yaml install.sh ${{ secrets.SSH_USENAME }}@95.85.121.201:/path/to/destination

      - name: Run install.sh
        run: |
          ssh -p 2222 ${{ secrets.SSH_USENAME }}@95.85.121.201 'cd /path/to/destination && chmod +x install.sh && ./install.sh'
