name: Deploy to Linux via SSH

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Set up SSH connection
        uses: webfactory/ssh-agent@v0.5.1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          
      - name: Add known hosts
        run: echo "${{ secrets.SSH_KEY }}" >> $HOME/.ssh/known_hosts
          
      - name: Create destination directory
        uses: appleboy/ssh-action@master
        with:
          host: 95.85.121.201
          port: 2222
          username: ${{ secrets.SSH_USENAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            mkdir -p /home/test/destination
            
      - name: Create temporary key file
        run: echo "$SSH_PRIVATE_KEY" > temp_key
            
      - name: Copy files via SSH with password using expect
        env:
          PASS_KEY: ${{ secrets.PASS_KEY }}
        run: |
          sudo apt-get -y install expect
          |
          expect -c '
            spawn scp -r -P 2222 docker-compose.yaml install.sh ${{ secrets.SSH_USENAME }}@95.85.121.201:/path/to/destination
            expect "password:"
            send "$env(PASS_KEY)\n"
            interact

      - name: SSH into the server and run script
        uses: appleboy/ssh-action@master
        with:
          host: 95.85.121.201
          port: 2222
          username: ${{ secrets.SSH_USENAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/test/destination
            chmod +x install.sh
            ./install.sh
            
      - name: Clean up temporary key file
        run: rm temp_key
