name: Deploy to Linux via SSH

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Set up SSH connection
        uses: webfactory/ssh-agent@v0.5.1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add known hosts
        run: echo "${{ secrets.SSH_PRIVATE_KEY }}" >> $HOME/.ssh/known_hosts

      - name: Copy files via SSH
        uses: appleboy/scp-action@master
        with:
          host: 95.85.121.201
          port: 2222
          username: ${{ secrets.SSH_USENAME }}
          password: ${{ secrets.PASS_KEY }}
          source: |
            ./docker-compose1.yaml
            ./install.sh
          target: /home/test/destination
          remote: /home/test/destination
